[tool.poetry]
name = "datascience-python-renku-dependencies"
version = "0.0.1"
description = "Basic Python datascience dependencies for renkulab.io"
authors = ["Renku developers <hello@renku.io>"]
license = "Apache 2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
pandas = "^2.3.3"
numpy = "^2.3.4"
scipy = "^1.16.2"
scikit-learn = "^1.7.2"
plotly = "^6.3.1"
transformers = "^4.57.1"
matplotlib = "^3.10.7"
seaborn = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
